idea-box/config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get "/signup", to: "users#new"
  get "/profile", to: "users#show"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :ideas
  resources :users, only: [:create]
  resources :categories
  resources :images
end

idea-box/app/models/category.rb
class Category < ActiveRecord::Base
  has_many  :ideas, dependent: :destroy
  validates :name, presence: true
end

idea-box/app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :idea_images
  has_many   :images, through: :idea_images
  validates  :title, :description, :user_id, :category_id, presence: true
end

idea-box/app/models/idea_image.rb
class IdeaImage < ActiveRecord::Base
  belongs_to :idea
  belongs_to :image
end

idea-box/app/models/image.rb
class Image < ActiveRecord::Base
  has_many :idea_images
  has_many  :ideas, through: :idea_images
  validates :address, presence: true
end

idea-box/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many  :ideas
  has_many  :categories, through: :ideas
  validates :username, :password, presence: true
end

idea-box/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

idea-box/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, only: [:show, :edit, :update, :destroy]
  before_action :authorize?, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    if current_user
      @category = Category.new
    else
      render plain: "MUST BE ADMIN STINNETTE"
    end
  end

  def create
    @category = Category.create(category_params)
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
  end

  def update
    if @category.update(category_params)
      flash.notice = "Updated Category!"
      redirect_to categories_path
    else
      flash.now[:notice]
      render :edit
    end
  end

  def show

  end

  def destroy
    flash.notice = "YOU DELETED: #{@category.ideas.count} IDEAS!"
    ideas = @category.ideas
    ideas.each do |idea|
      idea.delete
    end
    @category.delete
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :category_id)
  end

  def load_category
    @category = Category.find(params[:id])
  end

  def authorize?
    if !current_user.admin?
      render plain: "GO AWAY HACKER STINNETTE"
    end
  end
end

idea-box/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :load_idea, only: [:show, :edit, :update, :destroy]
  before_action :authorize?, only: [:show, :edit, :update, :destroy]

  def new
    if current_user
      @idea = Idea.new(user_id: current_user.id)
      @categories = Category.all
    else
      render plain: "MUST BE LOGGED IN STINNETTE"
    end
  end

  def create
    @idea = Idea.create(idea_params)
    redirect_to profile_path
  end

  def edit
    @idea = Idea.find(params[:id])
    @categories = Category.all
  end

  def update
    if @idea.update(idea_params)
      flash.notice = "Updated Idea!"
      redirect_to profile_path
    else
      flash.now[:notice]
      render :edit
    end
  end

  def show

  end

  def destroy
    @idea.delete
    flash.notice = "YOU HAVE BEEN TERMINATED. STINNETTE"
    redirect_to profile_path
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description, :user_id, :category_id)
  end

  def load_idea
    @idea = Idea.find(params[:id])
  end

  def authorize?
    if @idea.user != current_user
      render plain: "GO AWAY HACKER STINNETTE"
    end
  end
end

idea-box/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :load_image, only: [:show, :edit, :update, :destroy]
  before_action :authorize?, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
  end

  def new
    if current_user
      @image = Image.new
    else
      render plain: "MUST BE ADMIN STINNETTE"
    end
  end

  def create
    @image = Image.create(image_params)
    redirect_to images_path
  end

  def edit
    @image = Image.find(params[:id])
    @images = Image.all
  end

  def update
    if @image.update(image_params)
      flash.notice = "Updated Image!"
      redirect_to images_path
    else
      flash.now[:notice]
      render :edit
    end
  end

  def show

  end

  def destroy
    @image.delete
    redirect_to images_path
  end

  private

  def image_params
    params.require(:image).permit(:address, :image_id)
  end

  def load_image
    @image = Image.find(params[:id])
  end

  def authorize?
    if !current_user.admin?
      render plain: "GO AWAY HACKER STINNETTE"
    end
  end
end

idea-box/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash.notice = "You remembered your password #{@user.username}"
      redirect_to profile_path
    else
      flash.now[:notice] = "Hacker Stinnette Detected."
      render :new
    end
  end

  def destroy
    session.clear
    flash.notice = "Successfully logged out. Why you leave? :("
    redirect_to root_path
  end
end

idea-box/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    session[:user_id] = user.id
    redirect_to "/profile"
  end

  def show
    if current_user
      @user = current_user
      @ideas = @user.ideas
    else
      render plain: "FORBIDDEN. Hacker Stinnette Detected"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

idea-box/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

idea-box/app/helpers/welcome_helper.rb
module WelcomeHelper
end

idea-box/app/views/categories/index.html.erb
<div class="jumbotron">
  <h1><strong>Welcome,</strong> <em>Admin</em></h1>
  <br>
  <a class="btn btn-danger" <%= link_to "Logout", logout_path, method: :delete %>
  <a class="btn btn-primary" <%= link_to "Create Category", new_category_path %></a>
  <br><br>
  <br>
  <div class="container">
      <div class="table responsive">
        <table class="table">
          <tr class="warning">
            <th>Name</th>
            <th>Change</th>
            <th>Terminate</th>
          </tr>
         <% @categories.each do |category| %>
           <tr class="success">
             <td> <%= link_to category.name, category_path(category) %> </td>
             <td> <%= link_to "Edit", edit_category_path(category) %> </td>
             <td> <%= link_to "Destroy", category_path(category), method: :delete %> </td>
           </tr>
         <% end %>
       </table>
     </div>
   </div>
 </div>

idea-box/app/views/categories/new.html.erb
<div class="jumbotron">
<h1>New Category!</h1>

<%= form_for @category do |f| %>
  <p><%= f.label :name %><br>
  <%= f.text_field :name %><br><br>
  <%= f.submit "Create Category" %></p>
<% end %>
<div>

idea-box/app/views/ideas/edit.html.erb
<br><br>
<div class="jumbotron">
  <div class="form-group">
    <%= form_for @idea do |f| %>
      <p><%= f.label :title %><br></p>
      <p><%= f.text_field :title %><br><br></p>
      <p><%= f.label :description %><br></p>
      <p><%= f.text_area :description %></p>
      <%= f.collection_select :category_id, @categories, :id, :name %><br><br>
      <br><br>
      <%= f.submit %>
    <% end %>
  </div>
</div>

idea-box/app/views/ideas/new.html.erb
<div class="jumbotron">
<h1>New Idea!</h1>

<%= form_for @idea do |f| %>
  <p><%= f.label :title %><br>
  <%= f.text_field :title %><br><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.hidden_field :user_id %><br>
  <%= f.collection_select :category_id, @categories, :id, :name %><br><br>
  <%= f.submit "Create Idea" %></p>
<% end %>
<div>

idea-box/app/views/ideas/show.html.erb
<div class="jumbotron">
  <h1>
    <%= @idea.title %><br><br>
  </h1>
  <p>
    <%= @idea.description %>
  </p>
</div>

idea-box/app/views/images/edit.html.erb
<br><br>
<div class="jumbotron">
  <div class="form-group">
    <%= form_for @image do |f| %>
      <p><%= f.label :address %><br></p>
      <p><%= f.text_field :address %><br><br></p>
      <br><br>
      <%= f.submit %>
    <% end %>
  </div>
</div>

idea-box/app/views/images/index.html.erb
<div class="jumbotron">
  <h1><strong>Welcome,</strong> <em>Admin</em></h1>
  <br>
  <a class="btn btn-danger" <%= link_to "Logout", logout_path, method: :delete %>
  <a class="btn btn-primary" <%= link_to "Create Image", new_image_path %></a>
  <br><br>
  <br>
  <div class="container">
      <div class="table responsive">
        <table class="table">
          <tr class="warning">
            <th>Address</th>
            <th>Change</th>
            <th>Terminate</th>
          </tr>
         <% @images.each do |image| %>
           <tr class="success">
             <td> <%= link_to image.address[0..10], image_path(image) %> </td>
             <td> <%= link_to "Edit", edit_image_path(image) %> </td>
             <td> <%= link_to "Destroy", image_path(image), method: :delete %> </td>
           </tr>
         <% end %>
       </table>
     </div>
   </div>
 </div>

idea-box/app/views/images/new.html.erb
<div class="jumbotron">
<h1>New Image!</h1>

<%= form_for @image do |f| %>
  <p><%= f.label :address %><br>
  <%= f.text_field :address %><br><br>
  <%= f.submit "Create Image" %></p>
<% end %>
<div>

idea-box/app/views/images/show.html.erb
<br>
<div class="jumbotron">
  <img src="<%= @image.address %>">
</div>

idea-box/app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
 <head>
   <title>IDEA BOX</title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-t    rack' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true     %>
   <%= csrf_meta_tags %>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
   <link rel="stylesheet" href="/custom.css">
</head>
<body>
  <nav id="capy" class="navbar navbar-inverse navbar-fixed-top">
       <div class="container">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="/" ><strong><%= flash.notice %></strong> IDEA BOX </a>
         </div>
         <div id="navbar" class="collapse navbar-collapse">
           <ul class="nav navbar-nav">
             <li><a href="/profile">Profile</a></li>
           </ul>
         </div>
       </div>
  </nav>


<%= yield %>

<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

idea-box/app/views/users/new.html.erb
<div class="jumbotron">
  <h1>Sign Up!</h1>
  <br>
  <%= form_for @user do |f| %>
    <%= f.label :username %><br>
    <%= f.text_field :username %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br><br>
    <%= f.submit "Sign up" %>
  <% end %>
</div>

idea-box/app/views/users/show.html.erb
<div class="jumbotron">
  <div class="profile-info">
    <br>
    <h1><strong> <%= @user.username %>'s </strong> <em>profile:</em> </h1>
    <br>
    <a class="btn btn-danger" <%= link_to "Logout", logout_path, method: :delete %></a>
    <a class="btn btn-primary" <%= link_to "Create Idea", new_idea_path %></a>
    <br><br>
    <% if current_user.admin? %>
       <a class="btn btn-success" <%= link_to "Category Console", categories_path %></a>
       <a class="btn btn-success" <%= link_to "Image Console", images_path %></a>
    <% end %>
  <br>
  <br>
  <br>
  <div class="container">
    <div class="table responsive">
      <table class="table">
        <tr class="warning">
          <th>Title</th>
          <th>Description</th>
          <th>Category</th>
          <th>Change</th>
          <th>Terminate</th>
        </tr>
       <% @ideas.each do |idea| %>
         <tr class="success">
           <td> <%= link_to idea.title, idea_path(idea) %> </td>
           <td> <%= idea.description %> </td>
           <td><strong> <%= idea.category.name %> </strong></td>
           <td> <%= link_to "Edit", edit_idea_path(idea) %> </td>
           <td> <%= link_to "Destroy", idea_path(idea), method: :delete %> </td>
         </tr>
       <% end %>
     </table>
   </div>
   </div>
  </div>
</div>

idea-box/app/views/welcome/index.html.erb
<div class="jumbotron">
  <% if current_user %>
    <h1> SUP SUP SUP </h1>
    <a class="btn btn-danger" <%= link_to "Logout", logout_path, method: :delete %></a>
  <% else %>
    <h1> WELCOME TO IDEA BOX </h1>
    <p>If you have an idea, put it in your box</p>
    <a class="btn btn-success" <%= link_to "Sign Up", signup_path %></a>
    <a class="btn btn-primary" <%= link_to "Login", login_path %></a>
  <% end %>
</div>